#!/usr/bin/env bash
# Stampcoin Platform v2.0 - Quick Reference

echo "======================================"
echo "  Stampcoin Platform v2.0 - Quick Ref"
echo "======================================"
echo ""

echo "📂 Project Structure:"
echo "├── server.js              - Express API server"
echo "├── wallet.js              - Wallet module"
echo "├── market.js              - Marketplace module"
echo "├── blockchain.js          - Token/blockchain module"
echo "├── public/                - Frontend assets"
echo "├── Dockerfile             - Production image"
echo "├── docker-compose.yml     - Dev stack"
echo "├── fly.toml              - Fly.io config"
echo "├── render.yaml           - Render config"
echo "└── .github/workflows/     - CI/CD"
echo ""

echo "🚀 Quick Start:"
echo "1. npm install"
echo "2. npm start"
echo "3. Open http://localhost:8080"
echo ""

echo "🐳 Docker:"
echo "   docker compose up       - Local development"
echo "   docker build -t app:latest . - Build image"
echo "   docker run -p 8080:8080 app - Run container"
echo ""

echo "☁️  Cloud Deploy:"
echo "   flyctl launch           - Deploy to Fly.io"
echo "   render.yaml             - Deploy to Render"
echo ""

echo "📊 API Endpoints (23 total):"
echo ""
echo "   Wallet (7):"
echo "   - POST   /api/wallet/create"
echo "   - GET    /api/wallet/:userId"
echo "   - POST   /api/wallet/transfer"
echo "   - GET    /api/wallet/:userId/transactions"
echo "   - POST   /api/wallet/:userId/stamps (token-protected)"
echo "   - GET    /api/wallets (token-protected)"
echo "   - POST   /api/wallet/:userId/topup (token-protected)"
echo ""
echo "   Market (7):"
echo "   - GET    /api/market/items"
echo "   - POST   /api/market/items"
echo "   - GET    /api/market/items/:itemId"
echo "   - PUT    /api/market/items/:itemId"
echo "   - POST   /api/market/items/:itemId/buy"
echo "   - DELETE /api/market/items/:itemId"
echo "   - GET    /api/market/transactions"
echo ""
echo "   Blockchain (5):"
echo "   - GET    /api/blockchain/info"
echo "   - GET    /api/blockchain/supply"
echo "   - POST   /api/blockchain/mint (token-protected)"
echo "   - GET    /api/blockchain/balance/:address"
echo "   - GET    /api/blockchain/mint/events (token-protected)"
echo ""
echo "   Core (4):"
echo "   - GET    /health"
echo "   - GET    /api/status"
echo "   - GET    /api/info"
echo "   - GET    /api/token"
echo ""

echo "🔑 Environment Variables:"
echo "   NODE_ENV              - production or development"
echo "   PORT                  - 8080 (default)"
echo "   SYNC_TOKEN            - Authentication token"
echo "   STP_CONTRACT_ADDRESS  - Token contract address"
echo "   ALLOWED_ORIGINS       - CORS comma-separated origins"
echo ""

echo "📝 Example API Calls:"
echo ""
echo "   Create wallet:"
echo "   curl -X POST http://localhost:8080/api/wallet/create \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"userId\":\"user1\",\"userName\":\"Alice\"}'"
echo ""
echo "   Get wallet:"
echo "   curl http://localhost:8080/api/wallet/user1"
echo ""
echo "   Transfer balance:"
echo "   curl -X POST http://localhost:8080/api/wallet/transfer \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"fromUserId\":\"user1\",\"toUserId\":\"user2\",\"amount\":100}'"
echo ""
echo "   List market items:"
echo "   curl http://localhost:8080/api/market/items"
echo ""
echo "   Get token info:"
echo "   curl http://localhost:8080/api/token"
echo ""
echo "   Mint tokens (requires auth):"
echo "   curl -X POST http://localhost:8080/api/blockchain/mint \\"
echo "     -H 'Authorization: Bearer YOUR_SYNC_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"toAddress\":\"user1\",\"amount\":1000}'"
echo ""

echo "📊 Stats:"
echo "   Dependencies: 2 (Express, CORS)"
echo "   API Endpoints: 23"
echo "   Build Time: ~40s"
echo "   Image Size: ~150MB"
echo "   Memory: ~50MB idle"
echo ""

echo "📖 Documentation:"
echo "   DEPLOYMENT.md       - Full deployment guide"
echo "   PROJECT_SUMMARY.md  - Project overview"
echo "   COMPLETION_REPORT.md - What was built"
echo "   .env.example        - Configuration template"
echo ""

echo "🔗 Links:"
echo "   GitHub: https://github.com/zedanazad43/stampcoin-platform"
echo "   Fly.io: https://fly.io"
echo "   Render: https://render.com"
echo ""

echo "✅ Status: Production Ready"
echo "Version: 2.0.0"
echo "======================================"
